// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: ReplicateRequest.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command uint32               `protobuf:"varint,1,opt,name=command,proto3" json:"command,omitempty"`
	Kvs     []*RepRequest_KVPair `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
	Check   int32                `protobuf:"varint,3,opt,name=check,proto3" json:"check,omitempty"`
}

func (x *RepRequest) Reset() {
	*x = RepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ReplicateRequest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepRequest) ProtoMessage() {}

func (x *RepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ReplicateRequest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepRequest.ProtoReflect.Descriptor instead.
func (*RepRequest) Descriptor() ([]byte, []int) {
	return file_ReplicateRequest_proto_rawDescGZIP(), []int{0}
}

func (x *RepRequest) GetCommand() uint32 {
	if x != nil {
		return x.Command
	}
	return 0
}

func (x *RepRequest) GetKvs() []*RepRequest_KVPair {
	if x != nil {
		return x.Kvs
	}
	return nil
}

func (x *RepRequest) GetCheck() int32 {
	if x != nil {
		return x.Check
	}
	return 0
}

type RepRequest_KVPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value   []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version int32  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *RepRequest_KVPair) Reset() {
	*x = RepRequest_KVPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ReplicateRequest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepRequest_KVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepRequest_KVPair) ProtoMessage() {}

func (x *RepRequest_KVPair) ProtoReflect() protoreflect.Message {
	mi := &file_ReplicateRequest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepRequest_KVPair.ProtoReflect.Descriptor instead.
func (*RepRequest_KVPair) Descriptor() ([]byte, []int) {
	return file_ReplicateRequest_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RepRequest_KVPair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RepRequest_KVPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RepRequest_KVPair) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_ReplicateRequest_proto protoreflect.FileDescriptor

var file_ReplicateRequest_proto_rawDesc = []byte{
	0x0a, 0x16, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x22, 0xb7, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2d, 0x0a, 0x03, 0x6b,
	0x76, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4b,
	0x56, 0x50, 0x61, 0x69, 0x72, 0x52, 0x03, 0x6b, 0x76, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x1a, 0x4a, 0x0a, 0x06, 0x4b, 0x56, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x0d, 0x5a, 0x0b,
	0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_ReplicateRequest_proto_rawDescOnce sync.Once
	file_ReplicateRequest_proto_rawDescData = file_ReplicateRequest_proto_rawDesc
)

func file_ReplicateRequest_proto_rawDescGZIP() []byte {
	file_ReplicateRequest_proto_rawDescOnce.Do(func() {
		file_ReplicateRequest_proto_rawDescData = protoimpl.X.CompressGZIP(file_ReplicateRequest_proto_rawDescData)
	})
	return file_ReplicateRequest_proto_rawDescData
}

var file_ReplicateRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ReplicateRequest_proto_goTypes = []interface{}{
	(*RepRequest)(nil),        // 0: protobuf.RepRequest
	(*RepRequest_KVPair)(nil), // 1: protobuf.RepRequest.KVPair
}
var file_ReplicateRequest_proto_depIdxs = []int32{
	1, // 0: protobuf.RepRequest.kvs:type_name -> protobuf.RepRequest.KVPair
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ReplicateRequest_proto_init() }
func file_ReplicateRequest_proto_init() {
	if File_ReplicateRequest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ReplicateRequest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ReplicateRequest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepRequest_KVPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ReplicateRequest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ReplicateRequest_proto_goTypes,
		DependencyIndexes: file_ReplicateRequest_proto_depIdxs,
		MessageInfos:      file_ReplicateRequest_proto_msgTypes,
	}.Build()
	File_ReplicateRequest_proto = out.File
	file_ReplicateRequest_proto_rawDesc = nil
	file_ReplicateRequest_proto_goTypes = nil
	file_ReplicateRequest_proto_depIdxs = nil
}
